config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
	devise_scope :user do
		get '/users/sign_out' => 'devise/sessions#destroy'
	end
	root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

	get 'search', to: 'search#index'
	resources :products
	resources :products do
		resources :variants, except: [:show]
	end
	resources :variants, except: [:show]
	resources :products do
		resources :comments
	end
	resources :cart_items
	get 'cart', to: 'cart#index'
	resources :wish_items
	get 'wish', to: 'wish#index'
	resources :orders
	resources :users

	namespace :admin do
    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'

    resources :users
    resources :products
    resources :orders
  end
end

app/models/age.rb
class Age < ApplicationRecord
	has_many :products
	validates :name, uniqueness: true, presence: true,
	length: { minimum: 3 }
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
	validates :name, uniqueness: true, presence: true,
	length: { minimum: 3 }
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	# has_many :products, :through => :cart_items


	def add_product(product_params)

		current_item = cart_items.find_by(variant_id: product_params[:product][:variant_id])

		if current_item
			product_params[:product][:action] == 'edit' ?
			current_item.quantity = product_params[:product][:quantity].to_i :
			current_item.quantity += product_params[:product][:quantity].to_i
			current_item.save
		else
			new_item = cart_items.create(product_id: product_params[:product][:product_id],variant_id: product_params[:product][:variant_id], quantity: product_params[:product][:quantity], cart_id: self.id)
		end

		new_item
	end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :product
	belongs_to :variant, optional: true
	belongs_to :cart

	def total_price
		product.price * quantity
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	validates :name, uniqueness: true, presence: true,
	length: { minimum: 3 }
	has_many :subcategories, dependent: :destroy
end

app/models/color.rb
class Color < ApplicationRecord
	has_many :variants
  	has_many :products, through: :variants
	validates :name, uniqueness: true, presence: true,
	length: { minimum: 3 }
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :commenter, presence: true,
	length: { minimum: 1 }
	validates :body, presence: true,
	length: { minimum: 3 }
	belongs_to :product
end

app/models/commentt.rb
class Comment < ApplicationRecord
	validates :commenter, presence: true,
	length: { minimum: 1 }
	validates :body, presence: true,
	length: { minimum: 3 }
	belongs_to :product
end

app/models/franchise.rb
class Franchise < ApplicationRecord
	has_many :products
	validates :name, uniqueness: true, presence: true,
	length: { minimum: 1 }
end

app/models/gender.rb
class Gender < ApplicationRecord
	has_many :products
	validates :name, uniqueness: true, presence: true,
	length: { minimum: 3 }
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :product
	belongs_to :variant
	belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :name, presence: true,
	length: { minimum: 1 }
	
	# enum gender_id: {'men': '0', 'women':'1', 'boys': '2', 'girls': '3', 'kids': '4'}
	# enum age_id: {'youth': '0', 'children':'1', 'infant_toddler': '2'}
	# enum color_id: {'black': '0', 'grey':'1', 'whiidte': '2', 'red': '3', 'pink': '4', 'red': '5', 'orange': '6', 'yellow': '7', 'green': '8', 'blue': '9', 'purple': '10', 'beige': '11', 'brown': '12', 'gold': '13', 'silve': '14', 'multicolor': '15'}
	has_many :variants, dependent: :destroy
  	has_many :colors, through: :variants
	belongs_to :gender, required: false
	belongs_to :age, required: false
	belongs_to :franchise, required: false
	belongs_to :category, required: false
	belongs_to :producttype, required: false
	belongs_to :brand, required: false
	belongs_to :sport, required: false
	include Filterable
	scope :gender, -> (status) { where gender_id: status }
	scope :age, -> (status) { where age: status }
	scope :franchise, -> (status) { where franchise_id: status }
	scope :producttype, -> (status) { where producttype_id: status }
	scope :brand, -> (status) { where brand_id: status }
	scope :category, -> (status) { where category_id: status }
	scope :subcategory, -> (status) { where subcategory_id: status }
	scope :sport, -> (status) { where sport_id: status }
	has_many :cart_items
	has_many :wish__items
end

app/models/producttype.rb
class Producttype < ApplicationRecord
	has_many :products
	validates :name, uniqueness: true, presence: true,
	length: { minimum: 3 }
end

app/models/sport.rb
class Sport < ApplicationRecord
	has_many :products
	validates :name, uniqueness: true, presence: true,
	length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.email = auth.info.email
  		user.password = Devise.friendly_token[0,20]
      user.name = auth.info.first_name
      user.lastname = auth.info.last_name
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      #user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
	 super.tap do |user|
		if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
			user.email = data["email"] if user.email.blank?
      user.name = data["name"] if user.name.blank?
    end
    end
  end

  has_many :orders
end

app/models/variant.rb
class Variant < ApplicationRecord
	belongs_to :product
	has_one_attached :avatar
	has_one_attached :hover
	has_many_attached :images
	has_many :cart_items
	has_many :wish__items
	belongs_to :color
	validates_numericality_of :stock, :price, greater_than_or_equal_to: 0
	
end

app/models/wish.rb
class Wish < ApplicationRecord
	has_many :wish_items
	# has_many :products, :through => :wish_items
	

	def add_product(product_params)

		current_item = wish_items.find_by(variant_id: product_params[:product][:variant_id])

		if current_item
			current_item.destroy
		else
			new_item = wish_items.create(product_id: product_params[:product][:product_id],variant_id: product_params[:product][:variant_id], wish_id: self.id)
		end
		
		new_item
	end

	
end

app/models/wish_item.rb
class WishItem < ApplicationRecord
	belongs_to :wish
	belongs_to :product
	belongs_to :variant
end

app/helpers/users_helper.rb
module UsersHelper

      # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/admin/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
      The form contains <%= pluralize(@order.errors.count, "error") %>.</div>
<ul>
    <% @order.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
 
<% end %></ul>
</div>
 
<% end %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :address, value: current_user.address %>
  <%= f.hidden_field :phone, value: current_user.phone %>
  <select name="order[method]" id="order_method_id" >
    <option value="">Chọn phương thức thanh toán</option>
<option value="giao hàng rồi trả phí">giao hàng rồi trả phí</option>
<option value="thẻ">thẻ</option></select>
  
  <%= f.hidden_field :status, value: 'đang xử lý' %>
  <%= f.submit 'Tạo đơn hàng',class: "materialize-btn materialize-btn-black" %>
<% end %>

app/views/admin/orders.html.erb
<div style="margin:10vh 10vw">

<h1> Tất cả Đơn hàng</h1>
<br>
<table border="1">
  <tr>
    <th>id order:</th>
    <th>Tên user:</th> 
    <th>Email user:</th> 
    <th>Địa chỉ giao hàng:</th>  
    <th>Số điện thoại xác nhận:</th>
    <th>Phương thức:</th>  
    <th>Trạng thái:</th>
    <th>Chi tiết:</th>
</tr>

<% @orders.order(:id).each do |o| %>

<tr>

    <td><%= o.id %></td>
    <td><%= o.user.name %></td>
    <td><%= o.user.email %></td>
    <td><%= o.address %></td>
    <td><%= o.phone %></td>
    <td><%= o.method %></td>
    <td><%= o.status %></td>
    <td><%= o.details %></td>


    
    <% if current_user.try(:admin?) %>
    <td><%= link_to 'Sửa', edit_order_path(o) %></td>
    <td><%= link_to 'Xóa', order_path(o),remote: true,
    method: :delete,
    data: { confirm: 'Bạn có chắc không?' } %></td>
    <% end %>
</tr>

<% end %>
</table>

</div>

app/views/admin/products.html.erb
<h1>Liệt kê các sản phẩm</h1>
<% if current_user.try(:admin?) %>
<%= link_to 'Sản phẩm mới', new_product_path %>
<% end %><br>
Tất cả sản phẩm: <%= @products.total_count %><br>
Sản phẩm mỗi trang: <%= @products.count %><br>
Tổng số trang: <%= @products.total_pages %><br>
Trang hiện tại: <%= @products.current_page %><br>
Trang tiếp theo: <%= @products.next_page  %><br>
Trang trước: <%= @products.prev_page %><br>
Có phải trang đầu không?: <%= @products.first_page?  %><br>
Có phải trang cuối không?: <%= @products.last_page? %><br>
Có phải trang ngoài khoảng?: <%= @products.out_of_range?  %><br>

Thông tin các mục trang: <%= page_entries_info @products, entry_name: 'item' %><br>
Đéo biết là cái gì: <%= rel_next_prev_link_tags @products %><br>

Đường dẫn trang tiếp theo: <%= path_to_next_page @products %><br>
Đường dẫn trang trước: <%= path_to_prev_page @products %><br>

<%= paginate @products %>
<table border="1">
  <tr>
    <th>id sản phẩm:</th>
    <th>Tên Sản Phẩm:</th> 
    <th>Avatar:</th>  
    <th>Hover:</th>
    <th>Images:</th>  
    <th>Dòng:</th>
    <th>Loại:</th>
    <th>Nhãn:</th>
    <th>Danh mục:</th>
    <th>Môn:</th>

</tr>

<% @products.order(:id).each do |product| %>
<tr>

    <td><%= product.id %></td>
    <td><%= product.name %></td>
    <td>
        <%= image_tag product.variants.first.avatar, size: "50x50" %>
    </td>
    <td>
        <%= image_tag product.variants.first.hover, size: "50x50" %>
    </td>
    <td>
        <% product.variants.first.images.each do |image| %>
            <%= image_tag image, size: "50x50" %>
        <% end %>
    </td>
    <td><%= product.franchise_id ? product.franchise.name: '' %></td>
    <td><%= product.producttype_id ? product.producttype.name: '' %></td>
    <td><%= product.brand_id ? product.brand.name: '' %></td>
    <td><%= product.category_id ? product.category.name: '' %></td>
    <td><%= product.sport_id ? product.sport.name: '' %></td>


    <td><a href="/products/<%= product.id %>?variant=<%= product.variants.first.id %>">Xem</a></td>
    <% if current_user.try(:admin?) %>
    <td><%= link_to 'Sửa', edit_product_path(product) %></td>
    <td><%= link_to 'Xóa', product_path(product),remote: true,
    method: :delete,
    data: { confirm: 'Bạn có chắc không?' } %></td>
    <% end %>
</tr>
<% end %>
</table>
<br>
<%= link_to 'Trở lại', root_path %>

app/views/admin/users.html.erb
<div style="margin:10vh 10vw">

<h1> Tất cả Người dùng</h1>
<br>
<table border="1">
  <tr>
    <th>id:</th>
    <th>email:</th> 
    <th>created_at:</th> 
    <th>updated_at:</th>  
    <th>Quyền:</th>
    <th>provider:</th>  
    <th>name:</th>
    <th>lastname:</th>
    <th>address:</th>
    <th>phone:</th>
</tr>

<% @users.order(:id).each do |o| %>

<tr>

    <td><%= o.id %></td>
    <td><%= o.email %></td>
    <td><%= o.created_at %></td>
    <td><%= o.updated_at %></td>
    <td><%= o.admin ? 'Quản trị viên' : 'Người dùng' %></td>
    <td><%= o.provider %></td>
    <td><%= o.name %></td>
    <td><%= o.lastname %></td>
    <td><%= o.address %></td>
    <td><%= o.phone %></td>


    <td><%= link_to 'Xem', user_path(o) %></td>
    <td><%= link_to 'Sửa', edit_user_path(o) %></td>
    <td><%= link_to 'Xóa', user_path(o),remote: true,
    method: :delete,
    data: { confirm: 'Bạn có chắc không?' } %></td>
</tr>

<% end %>
</table>

</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this region from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>