config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
	devise_scope :user do
		get '/users/sign_out' => 'devise/sessions#destroy'
	end
	root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

	get 'search', to: 'search#index'
	resources :products
	resources :products do
		resources :variants, except: [:show]
	end
	resources :variants, except: [:show]
	resources :products do
		resources :comments
	end
	resources :cart_items
	get 'cart', to: 'cart#index'
	resources :wish_items
	get 'wish', to: 'wish#index'
	resources :orders
	resources :users

	namespace :admin do
    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'

    resources :users
    resources :products
    resources :orders
  end
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :authenticate_user!
	def index
		@orders = Order.all
	end

	def show
		@order = Order.find(params[:id])
	end

	def new
		@order = Order.new
	end

	def edit
		@order = Order.find(params[:id])
	end

	def create
		@order = Order.new(order_params)

		if @order.save
			redirect_to orders_path
		else
			render 'new'
		end
	end

	def update
		@order = Order.find(params[:id])

		if @order.update(order_params)
			redirect_to admin_orders_path
		else
			render 'edit'
		end
	end

	def destroy
		@order = Order.find(params[:id])
		@order.destroy

		redirect_to request.referrer
	end

	private
	def order_params
		params.require(:order).permit(:user_id, :address, :phone, :method, :status, :details)
	end
	def filtering_params(params)
		params.slice(:status, :location, :starts_with)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	def index
		@orders = Order.all
	end

	def show
		@order = Order.find(params[:id])
	end

	def new
		@order = Order.new
	end

	def edit
		@order = Order.find(params[:id])
	end

	def create
		@order = Order.new(order_params)

		if @order.save 
			redirect_to orders_path
		else
			render 'new'
		end
	end
	
	def update
		@order = Order.find(params[:id])
		
		if @order.update(order_params)
			redirect_to admin_orders_path
		else
			render 'edit'
		end
	end
	
	def destroy
		@order = Order.find(params[:id])
		@order.destroy
		
		redirect_to request.referrer
	end
	
	private
	def order_params
		params.require(:order).permit(:user_id, :address, :phone, :method, :status, :details)
	end
	def filtering_params(params)
		params.slice(:status, :location, :starts_with)
	end
end

app/views/admin/orders/_form.html.erb
<% details = '' %>
<% tonggiaban = 0 %>
<% tonggiagoc = 0 %>
<% i = 0 %>
<% @cart.cart_items.order(:id).each do |cart_item| %>
        <% giaban = cart_item.variant.price %>
        <% if !cart_item.variant.originalprice.nil? then giagoc = cart_item.variant.originalprice end %>
        <% soluong = cart_item.quantity %>
        <% tonggiaban += soluong * giaban %> 
        <% giagoc ? tonggiagoc += soluong * giagoc : tonggiagoc += soluong * giaban %>
        <% details<<cart_item.product.name %>
        <% details<<'(' %>
        <% details<<cart_item.variant_id.to_s %>
        <% details<<')' %>
        <% details<<'x' %>
        <% details<<soluong.to_s %>
        <% details<<',' %>
<% end %>

    <br>
        <% details<<'TỔNG: ' %>

        <% details<<number_to_currency(tonggiaban*23000, precision: 0, separator: ',',delimiter: '.', unit: '₫', format: "%n %u").to_s %>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
      The form contains <%= pluralize(@order.errors.count, "error") %>.</div>
<ul>
    <% @order.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
 
<% end %></ul>
</div>
 
<% end %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :details, value: details %>
  <%= f.hidden_field :address, value: current_user.address %>
  <%= f.hidden_field :phone, value: current_user.phone %>
  <select name="order[method]" id="order_method_id" >
    <option value="thanh toán khi giao hàng">Chọn phương thức thanh toán</option>
<option value="thanh toán khi giao hàng">thanh toán khi giao hàng</option>
<option value="thẻ">thẻ</option></select>
  
  <%= f.hidden_field :status, value: 'đang xử lý' %>
  <%= f.submit 'Tạo đơn hàng',class: "materialize-btn materialize-btn-black" %>
<% end %>

app/views/admin/orders/_formedit.html.erb
<% details = '' %>
<% tonggiaban = 0 %>
<% tonggiagoc = 0 %>
<% i = 0 %>
<% @cart.cart_items.order(:id).each do |cart_item| %>
        <% giaban = cart_item.variant.price %>
        <% if !cart_item.variant.originalprice.nil? then giagoc = cart_item.variant.originalprice end %>
        <% soluong = cart_item.quantity %>
        <% tonggiaban += soluong * giaban %> 
        <% giagoc ? tonggiagoc += soluong * giagoc : tonggiagoc += soluong * giaban %>
        <% details<<cart_item.product.name %>
        <% details<<'(' %>
        <% details<<cart_item.variant_id.to_s %>
        <% details<<')' %>
        <% details<<'x' %>
        <% details<<soluong.to_s %>
        <% details<<',' %>
<% end %>

    <br>
        <% details<<'TỔNG: ' %>

        <% details<<number_to_currency(tonggiaban*23000, precision: 0, separator: ',',delimiter: '.', unit: '₫', format: "%n %u").to_s %>

<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger">
      The form contains <%= pluralize(@order.errors.count, "error") %>.</div>
<ul>
    <% @order.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
 
<% end %></ul>
</div>
 
<% end %>
  <%= f.label :user_id %><%= f.text_area :user_id %>
  <%= f.label :details %><%= f.text_area :details %>
  <%= f.label :address %><%= f.text_area :address %>
  <%= f.label :phone %><%= f.text_area :phone %>

  
  <select name="order[method]" id="order_method_id" >
    <option value="thanh toán khi giao hàng">Chọn phương thức thanh toán</option>
<option value="thanh toán khi giao hàng">thanh toán khi giao hàng</option>
<option value="thẻ">thẻ</option></select>

<select name="order[status]" id="order_status_id" >
    <option value="đang xử lý">Thay đổi trạng thái đơn hàng</option>
<option value="đã hoàn thành">đã hoàn thành</option>
<option value="đang xử lý">đang xử lý</option></select>
  
  
  <%= f.submit 'Cập nhật đơn hàng',class: "materialize-btn materialize-btn-black" %>
<% end %>

app/views/admin/orders/edit.html.erb
<% if current_user.try(:admin?) %>
<h1>Sửa đơn hàng</h1>

<%= render 'formedit' %>

<%= link_to 'Trở lại', products_path %>
<% else %>
<h1 style="text-align: center;">Page Not Found</h1>
<h3 style="text-align: center;">The page you requested does not exist</h1>
<% end %>

app/views/admin/orders/index.html.erb
<div style="margin:10vh 10vw">

<h1>Đơn hàng của bạn</h1>
<br>
<table border="1">
  <tr>
    <th>id order:</th>
    <th>Tên user:</th>
    <th>Email user:</th>
    <th>Địa chỉ giao hàng:</th>
    <th>Số điện thoại xác nhận:</th>
    <th>Phương thức:</th>
    <th>Trạng thái:</th>
    <th>Chi tiết:</th>
</tr>

<% @orders.each do |o| %>

<tr>

    <td><%= o.id %></td>
    <td><%= o.user.name %></td>
    <td><%= o.user.email %></td>
    <td><%= o.address %></td>
    <td><%= o.phone %></td>
    <td><%= o.method %></td>
    <td><%= o.status %></td>
    <td><%= o.details %></td>



    <% if current_user.try(:admin?) %>
    <td><%= link_to 'Sửa', edit_order_path(o) %></td>
    <td><%= link_to 'Xóa', order_path(o),
    method: :delete,
    data: { confirm: 'Bạn có chắc không?' } %></td>
    <% end %>
</tr>

<% end %>
</table>

</div>

app/views/admin/orders/new.html.erb
<% provide(:title, 'Kiểm tra đơn hàng') %>
<% provide(:button_text, 'Tạo đơn hàng') %>
<div style="margin:10vh 10vw">

<% if current_user.address.blank? or current_user.phone.blank?  then %>
<h1>Hãy nhập đầy đủ địa chỉ, số điện thoại của bạn trước khi quay lại tạo đơn hàng tại:</h1>
<a href="/users/edit"><button class="materialize-btn materialize-btn-black">Chỉnh sửa tài khoản</button></a>
<% else %>
	<h1>Hãy kiểm tra thông tin của bạn</h1>
	<p><%= current_user.name %> <%= current_user.lastname %></p>
	<p><%= current_user.address %></p>
	<p><%= current_user.phone %></p>
	<div class="row">
	<div class="col-md-6 col-md-offset-3">
	    <%= render 'form' %></div>
	</div>
<% end %>


</div>