config/routes.rb
Rails.application.routes.draw do
	devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
	devise_scope :user do
		get '/users/sign_out' => 'devise/sessions#destroy'
	end
	root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

	get 'search', to: 'search#index'
	resources :products
	resources :products do
		resources :variants, except: [:show]
	end
	resources :variants, except: [:show]
	resources :products do
		resources :comments
	end
	resources :cart_items
	get 'cart', to: 'cart#index'
	resources :wish_items
	get 'wish', to: 'wish#index'
	resources :orders
	resources :users

	namespace :admin do
    root 'static_pages#home'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/contact', to: 'static_pages#contact'

    resources :users
    resources :products
    resources :orders
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  		user.email = auth.info.email
  		user.password = Devise.friendly_token[0,20]
      user.name = auth.info.first_name
      user.lastname = auth.info.last_name
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      #user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
	 super.tap do |user|
		if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
			user.email = data["email"] if user.email.blank?
      user.name = data["name"] if user.name.blank?
    end
    end
  end

  has_many :orders
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.order(:id).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account!'
      redirect_to(root_url)

    else
      render 'new'
    end
  end

  def edit
    @user = User.find( params[:id] )
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params) # returns true only on succesful update!
      # Handle a successful update.
      flash[:success] = "Profile has been successfully updated!"
      redirect_to (admin_users_url)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find( params[:id] ).destroy

    respond_to do |format|
      format.html {
        flash[:success] = 'User successfully deleted!'
        redirect_to (admin_users_url)
      }
      format.js
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :role,
                                 :password_confirmation)
  end

  # Before filters

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user.admin?
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)

		if @user.save 
			redirect_to users_path
		else
			render 'new'
		end
	end
	
	def update
		@user = User.find(params[:id])
		
		if @user.update(user_params)
			redirect_to admin_users_path
		else
			render 'edit'
		end
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		
		redirect_to request.referrer
	end
	
	private
	def user_params
		params.require(:user).permit(:email, :admin, :name, :lastname, :address, :phone)
	end

end

app/helpers/users_helper.rb
module UsersHelper

      # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/admin/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>s

app/views/admin/users/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
  <% else %>
      <%= render 'follow' %>
  <% end %>
</div>

app/views/admin/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: @user %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
	<td><%= user.id %></td>
	<td><%= gravatar_for user, size: 80 %></td>
	<td><%= link_to user.name, user %></td>
	<td><%= user.email %></td>
	<!-- <td><%= user.password_digest %></td> -->
	<td><%= user.role %></td>
	<td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
	<td>
	<% if current_user.id != user.id %>
	<%= link_to 'Delete', admin_user_path(user),
	        remote: true,
	        method: :delete,
	        data: { confirm: 'You sure?' },
	        class: "user-#{user.id}" %>
	<% end %>
	</td>
</tr>

app/views/admin/users/destroy.js.erb
$('.user-<%= @user.id %>').closest('tr').remove();

app/views/admin/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% if current_user.admin? %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails">change</a>
    </div>
  </div>
</div>
<% else %>
<h1>PAGE NOT FOUND</h1>
<% end %>

app/views/admin/users/index.html.erb
<% provide(:title, 'All users') %>
<% if current_user.admin? %>
<h1>All users</h1>
<%= link_to 'New user', new_admin_user_path %>
<%= paginate @users %>
<%= page_entries_info @users, entry_name: 'item' %>
<ul class="users">
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <!-- <th scope="col">Gravatar</th> -->
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <!-- <th scope="col">Pasword</th> -->
      <th scope="col">Admin</th>
      <th></th>
      <th></th>
      <!-- <th></th> -->
    </tr>
  </thead>
  <% @users.order(:id).each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <!-- <td><%= gravatar_for user, size: 80 %></td> -->
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.admin %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td>
      <% if current_user.id != user.id %>
      <%= link_to 'Delete', admin_user_path(user),
              remote: true,
              method: :delete,
              data: { confirm: 'You sure?' },
              class: "user-#{user.id}" %>
      <% end %>
      </td>
    </tr>
  <% end %>
 </table>
</ul>
<% else %>
<h1>PAGE NOT FOUND</h1>
<% end %>

app/views/admin/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% if current_user.admin? %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<% else %>
<h1>PAGE NOT FOUND</h1>
<% end %>

app/views/admin/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
    <% end %>
  </div>
</div>

app/views/admin/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
                <%= link_to gravatar_for(user, size: 30), user %>
            <% end %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
    <% end %>
  </div>
</div>